feat: create a routine for testing the nsfw model accuracy
WolfEngine/wolf pull request #22
Opened 2023-05-30 13:11 UTC by MBSM110

# Pull Request Checklist

Please check if your pull request fulfils the following requirements:

  * [x] The commit message follows our guidelines: <https://gitlab.playpod.ir/alpha/backend/nakama-module-next/-/blob/main/CONTRIBUTING.md#commit-message-format>
  * [x] Tests for the changes have been added / updated (for feat / fix / refactor)
  * [x] Docs for the changes have been added / updated (for feat / fix / refactor)

## Pull Request Type

What kind of change does this pull request introduce?

  * [ ] Build: Changes that affect the build system or external dependencies
  * [ ] CD: Changes to our CD configuration files and scripts
  * [ ] CI: Changes to our CI configuration files and scripts
  * [ ] Docs: Documentation only changes
  * [x] Feat: A new feature
  * [ ] Fix: A bug fix
  * [ ] Perf: A code change that improves performance
  * [ ] Refactor: A code change that neither fixes a bug nor adds a feature
  * [ ] Test: Adding missing tests or correcting existing tests

## What is the current behaviour?

Issue #20

## What is the new behaviour?

## Does this Pull Request introduce a breaking change?

  * [ ] Yes
  * [x] No

## Other information

Closes #20

2023-05-31 09:25 UTC, PooyaEimandar commented on wolf/ml/w_utilities.hpp
> +W_API auto create_labeled_image_text(
using `auto` excessively can sometimes reduce code readability and may not always be appropriate, especially in cases where explicit type declarations are preferred for clarity. You are using `auto` along with defining return type. 

which one is better?
W_API std::vector<int> function() { return std::vector<int>(); }
or
W_API auto function()  -> std::vector<int> { return std::vector<int>(); }
or 
W_API auto function()  { return std::vector<int>();}

2023-05-31 09:25 UTC, PooyaEimandar commented on wolf/ml/w_utilities.hpp
> +W_API auto create_labeled_image_text(
@MBSM110 @cthulhu-irl

2023-05-31 09:40 UTC, cthulhu-irl commented on wolf/ml/w_utilities.hpp
> +W_API auto create_labeled_image_text(
@PooyaEimandar 

I would advise to use the following guideline:

first one is suited best for simple types like bool or w_status or other short name non-templated types,
second one for the templated/complex types and long names,
third one only when the type is unknown and its declaration would require complex syntax like `decltype`.

and if only one style must be followed/enforced, second one seems to be best suited.

2023-05-31 09:53 UTC, cthulhu-irl commented on wolf/ml/w_utilities.hpp
> +W_API auto create_labeled_image_text(
@PooyaEimandar 

I would prefer second one. trailing return type is well suited for simple and short type names as well as complex (templated/etc) and long type names. and when the type is unknown or its declaration doesn't help with readability (like returning a combined ranges iterator) the third style matches it.

iirc it also can be enforced by clang-format/tidy.

2023-06-07 12:15 UTC, MBSM110 commented on wolf/ml/test/w_utilities_test.hpp
> +  std::vector<int> value = get_env_vector_of_int(key.c_str());
The 'env' files present in the test directory are files that are stored within the project itself, making them an internal resource. These files maintain a constant state and are not dependent on any external resources.

2023-06-07 13:01 UTC, MBSM110 commented on wolf/ml/w_utilities.cpp
> +		std::cout << "The path to images is not exist!!!" << std::endl;
I would open a refactor task for modify this kind of "return error code".

2023-06-07 13:34 UTC, MBSM110 commented on wolf/ml/w_utilities.cpp
> +		case 49:
I am not convinced that the way you suggest to change the code could resolve the issue you are considering.

2023-06-07 13:54 UTC, cthulhu-irl commented on wolf/ml/w_utilities.cpp
> +		case 49:
self-explaining symbol names are durable, comments are not. for example typos in symbol names are caught by the compiler while comments can not be, being local to a specific function as the above code or shared throughout the codebase.

And as a general practice I'd also suggest to rather use comments to explain `why` and not the `what`, and embrace the language features and type system to properly address and/or convey meaning, usage, restrictions, and etc.

For this specific case, it's not vital (seemingly at least) but only suggested.

read more at here: https://refactoring.guru/replace-magic-number-with-symbolic-constant

2023-06-08 06:34 UTC, cthulhu-irl requested changes

2023-06-08 06:34 UTC, cthulhu-irl commented on wolf/ml/w_utilities.cpp
> +	}
refactor to match wolf's style.

2023-06-08 06:34 UTC, cthulhu-irl commented on wolf/ml/w_utilities.cpp
> +	{
refactor to match wolf's style.

2023-06-08 06:34 UTC, cthulhu-irl commented on wolf/ml/w_utilities.cpp
> +	}
refactor to match wolf's style.

2023-06-08 06:34 UTC, cthulhu-irl commented on wolf/ml/w_utilities.cpp
> +	{
refactor to match wolf's style.

2023-06-08 06:34 UTC, cthulhu-irl commented on wolf/ml/nudity_detection/w_nudity_detection.hpp
> +  */
rewrite in wolf's documentation style: https://github.com/WolfEngine/wolf/blob/main/wolf/media/w_openal.hpp#L51-L56

2023-06-08 06:34 UTC, cthulhu-irl commented on wolf/ml/w_utilities.hpp
> +*/
rewrite in wolf's documentation style: https://github.com/WolfEngine/wolf/blob/main/wolf/media/w_openal.hpp#L51-L56

2023-06-08 06:34 UTC, cthulhu-irl commented on wolf/ml/w_utilities.hpp
> +*/
rewrite in wolf's documentation style: https://github.com/WolfEngine/wolf/blob/main/wolf/media/w_openal.hpp#L51-L56

2023-06-08 06:46 UTC, MBSM110 commented on wolf/ml/w_utilities.cpp
> +	}
I should change the style in my whole folder. I will open a pull request for this later.

2023-06-08 06:47 UTC, MBSM110 commented on wolf/ml/w_utilities.hpp
> +*/
I should change the style in my whole folder. I will open a pull request for this later.

2023-06-08 06:58 UTC, cthulhu-irl approved these changes
add issues for the following:
 - refactor ml code and documentation style
 - refactor to embrace error handling
 - refactor to embrace single responsibility principle (configuration and parameters instead of depending on env/file/etc)

2023-06-08 10:22 UTC, closed without merging