feat: add redis client
WolfEngine/wolf pull request #34
Opened 2023-06-14 21:29 UTC by PooyaEimandar

# Pull Request Checklist

Please check if your pull request fulfils the following requirements:

  * [ ] Tests for the changes have been added / updated (for feat / fix / refactor)
  * [ ] Docs for the changes have been added / updated (for feat / fix / refactor)

## Pull Request Type

What kind of change does this pull request introduce?

  * [ ] Build: Changes that affect the build system or external dependencies
  * [ ] CD: Changes to our CD configuration files and scripts
  * [ ] CI: Changes to our CI configuration files and scripts
  * [ ] Docs: Documentation only changes
  * [x] Feat: A new feature
  * [ ] Fix: A bug fix
  * [ ] Perf: A code change that improves performance
  * [ ] Refactor: A code change that neither fixes a bug nor adds a feature
  * [ ] Test: Adding missing tests or correcting existing tests

## What is the current behaviour?

Issue #31

## What is the new behaviour?

## Does this Pull Request introduce a breaking change?

  * [ ] Yes
  * [x] No

## Other information

Closes #31

2023-06-17 14:19 UTC, PooyaEimandar commented
@cthulhu-irl please improve code coverage in another issue

2023-06-18 07:55 UTC, cthulhu-irl requested changes

2023-06-18 07:55 UTC, cthulhu-irl commented on wolf/system/db/w_redis_client.hpp
> +  W_API auto connect() -> boost::asio::awaitable<boost::leaf::result<int>> {
what does the returned `int` represent?

it seems to just be `0` if this method succeeds, and otherwise there would be no value as it'd be an error.

please use `void` if possible or a void type, e.g. `struct regular_void {};` (or some better name), if the value must be assignable.

2023-06-18 07:55 UTC, cthulhu-irl commented on wolf/system/db/w_redis_client.hpp
> +      -> boost::asio::awaitable<boost::leaf::result<int>> {
I'd suggest adding an overload for a simplified version of request? taking a string instead of a `boost::redis::request`.

this helps both in usage and having a consistent and well abstracted api that doesn't rely on third-party (to not to enforce user to use the same third-party).

2023-06-18 09:21 UTC, PooyaEimandar commented on wolf/system/db/w_redis_client.hpp
> +  W_API auto connect() -> boost::asio::awaitable<boost::leaf::result<int>> {
Most of the functions in Wolf, including but not limited to those related to ffmpeg, gamepad and etc, return error codes. It is recommended to return error codes consistently, even when there is no error (returning zero), to ensure compatibility when using different functions with Boost Leaf macros. Otherwise, you may encounter mismatched return results.

2023-06-18 09:28 UTC, PooyaEimandar commented on wolf/system/db/w_redis_client.hpp
> +      -> boost::asio::awaitable<boost::leaf::result<int>> {
Unlike in Wolf2, we don't want to wrap everything in private mode. Instead, we aim to make them easily accessible for other developers. The boost::redis::request already provides a mechanism for executing batches of commands. Therefore, adding the overhead of std::string would be pointless, as we should support batch mode commands again.

2023-06-18 09:43 UTC, PooyaEimandar commented on wolf/system/db/w_redis_client.hpp
> +          this->_config.addr.host, this->_config.addr.port, e.what());
Our naming code style in wolf follows the following conventions:
```
s_global_static_variable_name
_private_variable_name
public_variable_name
```
`this` will be used for both public and private local variables.

2023-06-18 09:45 UTC, PooyaEimandar commented on wolf/cmake/system.cmake
> +            GIT_TAG        develop
Master was not stable with new version redis.

2023-06-18 09:57 UTC, PooyaEimandar commented on wolf/system/db/w_redis_client.hpp
> +      boost::asio::deferred_t::as_default_on_t<boost::redis::connection>;
The name `connection_type` appears to be used for an `enum`. To avoid any potential conflicts with `boost::redis::connection`, will be renamed to `connection_t`.

2023-06-18 09:59 UTC, PooyaEimandar commented on wolf/system/db/w_redis_client.hpp
> +  // move constructor
no problem

2023-06-18 10:35 UTC, cthulhu-irl commented on wolf/cmake/system.cmake
> +            GIT_TAG        develop
`master` branch is also an on development branch and changes over time. maybe consider `v1.4.1`?

2023-06-18 10:38 UTC, cthulhu-irl commented on wolf/cmake/system.cmake
> +            GIT_TAG        develop
we also can postpone this to when we add `dependabot` or a similar dependency/version monitoring solution. although I'd personally prefer version pinning even without version monitoring, due to the above stated reasons (build consistency over time).

2023-06-18 10:45 UTC, cthulhu-irl commented on wolf/system/db/w_redis_client.hpp
> +          this->_config.addr.host, this->_config.addr.port, e.what());
"local variables" refers to variables defined in the scope of a function (or any executable routine). I guess you're referring to member variables.

overall I'd highly suggest not to mix `_private_member_variable_name` with `_local_variable_name`. it's genuinely confusing and quite hard to distinguish while reading the code, specially when it's being modified.

2023-06-18 10:53 UTC, cthulhu-irl commented on wolf/system/db/w_redis_client.hpp
> +  W_API auto connect() -> boost::asio::awaitable<boost::leaf::result<int>> {
I would argue that the rest of the codebase should eventually change too, and it's odd that this would cause inconsistency problems in build.

but about `BOOST_LEAF_*`, may I ask for a (small) code snippet demonstrating that mismatch in return type?

2023-06-18 11:08 UTC, cthulhu-irl commented on wolf/system/db/w_redis_client.hpp
> +      -> boost::asio::awaitable<boost::leaf::result<int>> {
> Unlike in Wolf2, we don't want to wrap everything in private mode. Instead, we aim to make them easily accessible for other developers.
Oh, great to hear, I was informed something else and this policy has changed.

> The boost::redis::request already provides a mechanism for executing batches of commands. Therefore, adding the overhead of std::string would be pointless, as we should support batch mode commands again.

Adding an overload for simpler use-cases (like single command instead of batching commands) would help greatly with little effort and almost no cost. it's just another overload and we're not removing the current one, it'll be retained.

example:
```cpp
redis_client.exec("SET x 1", ret_status);
```
instead of having to construct `boost::redis::request`:
```cpp
boost::redis::request req;
req.push("SET x 1");
redis_client.exec(req, ret_status);
```

It would also require reordering of arguments, `exec(ret, command)`, to allow parameter pack for `exec(ret, "SET x %d", x)` as an example.

2023-06-18 11:33 UTC, PooyaEimandar commented on wolf/system/db/w_redis_client.hpp
> +  W_API auto connect() -> boost::asio::awaitable<boost::leaf::result<int>> {
`boost::leaf::result<void>`  doesn't have `has_error()` function. Sometimes we need to use [this function](https://github.com/WolfEngine/wolf/blob/621072a3735572c851ee7dda98c5a370ee508055/wolf/system/test/redis.hpp#L26) instead of `BOOST_LEAF_` macros.

2023-06-18 13:44 UTC, cthulhu-irl approved these changes
Looks good to me.

I've left a few suggestions on `exec`'s api design. I'd be more than happy to discuss about them if you'd like too.

2023-06-18 13:44 UTC, cthulhu-irl commented on wolf/system/db/w_redis_client.hpp
> +                                                 boost::asio::use_awaitable);
I'd suggest to change the function signature as the following:
```cpp
template <class ...RetTypes>
auto exec(_Inout_ boost::redis::response<RetTypes...>& p_res, const boost::redis::request& p_req)
    -> boost::asio::awaitable<boost::leaf::result<int>>;
```

There are two reasons for this:
1. consistency between parameter ordering of the two overloads. the other overload being `template <class RetType, class ...CmdArgs> auto exec(_Inout_ boost::redis::response<RetType>& p_res, const std::string_view p_command, CmdArgs&& ...args)`.
2. Enforcing `boost::redis::request<RetTypes...>` instead of just generic `R` that matches everything, better informs about the api. and also more importantly helps with overload resolution and compiler errors.

We can also use a helper function `template <typename ...Args> auto single_redis_request(std::string_view p_command, Args&& ...p_args) -> boost::redis::request`, probably with a better name, if you'd find it a better solution.

Best case would be getting rid of out paramter altogether, and returning a tuple instead of int.

2023-06-18 13:44 UTC, cthulhu-irl commented on wolf/system/db/w_redis_client.hpp
> +      -> boost::asio::awaitable<boost::leaf::result<std::string>> {
This enforces string type, maybe use the following?
```cpp
template <typename T>
auto exec(const _In_ std::string_view& p_req)
      -> boost::asio::awaitable<boost::leaf::result<T>>;
```

For a sustainability and also user experience practice, I'd always try to keep the overloads similar, so user wouldn't need to know which will be called to adjust their usage. in here getting response via out parameter vs. return type.

This can be achieved by either of these two changes:
1. add out parameter to this overload.
2. return `std::tuple / boost::redis::response` from the other overload instead of out parameter.

2023-06-18 13:44 UTC, cthulhu-irl commented on wolf/system/db/w_redis_client.hpp
> +  std::shared_ptr<connection_t> _conn = nullptr;
I see the reason now. although it would be even better if the wording rather describe the why instead of the what.

for example:
"the connection object `_conn` will be shared with the async operation result being returned by command execution methods, and it must be kept alive despite the lifetime of an instance of this class."

The `boost::redis::config` type and `_config` name are already self-explanatory, no need for a comment.

2023-06-18 14:10 UTC, PooyaEimandar commented on wolf/system/db/w_redis_client.hpp
> +  std::shared_ptr<connection_t> _conn = nullptr;
In codebase of Wolf, we prefer to include comments even for self-explanatory code in order to prioritize readability goals. Can be improved when we want to build DOXYGEN.

2023-06-18 14:13 UTC, PooyaEimandar commented on wolf/system/db/w_redis_client.hpp
> +                                                 boost::asio::use_awaitable);
Thanks, please take the opportunity to enhance this design further in another refactor issue.

2023-06-18 14:14 UTC, PooyaEimandar commented on wolf/system/db/w_redis_client.hpp
> +      -> boost::asio::awaitable<boost::leaf::result<std::string>> {
Single Redis command returns std::string.

2023-06-19 09:33 UTC, merged