build: support OSX arm64
WolfEngine/wolf pull request #72
Opened 2023-07-20 13:09 UTC by PooyaEimandar

## Pull Request Checklist

What kind of change does this pull request introduce?

- [x] Build: Changes that affect the build system or external dependencies
- [ ] CI: Changes to our CI configuration files and scripts
- [ ] Docs: Documentation only changes
- [ ] Feat: A new feature
- [ ] Fix: A bug fix
- [ ] Perf: A code change that improves performance
- [ ] Refactor: A code change that neither fixes a bug nor adds a feature
- [ ] Test: Adding missing tests or correcting existing tests

## Does this Pull Request introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

Closes #71

2023-07-23 06:42 UTC, cthulhu-irl requested changes
would you also add OSX to cmake variable `DESKTOP` and/or update feature options accordingly so features supporting OSX would be built too?

2023-07-23 06:42 UTC, cthulhu-irl commented on CMakePresets.json
> +                "LIBRARY_TYPE": "STATIC",
please use `BUILD_SHARED_LIBS=OFF` to state static build. it's also off by default.

2023-07-27 09:20 UTC, PooyaEimandar commented on CMakePresets.json
> +                "BUILD_SHARED_LIBS": "OFF",
Thanks, fixed.

2023-07-27 09:22 UTC, PooyaEimandar commented on CMakeLists.txt
> +wolf_feature_option(WOLF_SYSTEM_GAMEPAD_VIRTUAL "Enable virtual gamepad simulator" OFF) #WIN64 AND NOT EMSCRIPTEN
Thanks, fixed.

2023-07-27 09:54 UTC, cthulhu-irl approved these changes

2023-07-27 09:55 UTC, merged